- hosts: webservers
  user: vagrant
  vars_files:
    - vars.yml

  tasks:
    - name: Download ruby
      get_url: "url={{ruby_url}} dest={{ruby_dir}}/ruby-{{ project_ruby }}.tar"

    - name: Extract ruby
      command: tar -zxf "{{ruby_dir}}/ruby-{{project_ruby}}.tar"

    - name: Make, configure, and install ruby
      command: "{{item}} chdir={{ruby_dir}}/ruby-{{project_ruby}}"
      with_items:
        - ./configure
        - make
        - sudo make install

    - name: Install bundler
      command: "sudo gem install bundler"
