- hosts: webservers
  user: vagrant
  sudo: True
  vars_files:
    - vars.yml
  vars:
    deploy: deploy
    home_dir: /home/deploy

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Linux packages
      action: apt pkg={{item}} state=installed
      with_items:
        - autoconf
        - automake
        - bison
        - build-essential
        - curl
        - gawk
        - git-core
        - git
        - libxml2-dev
        - libffi-dev
        - libyaml-dev
        - libssl-dev
        - libsqlite3-dev
        - libgdbm-dev
        - libncurses5-dev
        - libreadline6-dev
        - libtool
        - libyaml-dev
        - nfs-common # make virtualbox faster
        - pkg-config
        - sqlite3
        - vim
        - zlib1g-dev

    - name: remove existing ruby
      shell: rm -rf /opt/vagrant_ruby
